# Generated by Django 4.1.7 on 2023-05-10 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='core.medicine'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.purchase'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicine',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='core.company'),
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('medicine', 'sale')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseitem',
            unique_together={('medicine', 'purchase')},
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('type', 'brand_name', 'barcode')},
        ),
    ]
