# Generated by Django 4.1.7 on 2023-07-25 06:53

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='expiry_date',
            field=models.DateField(validators=[core.validators.validate_old_date]),
        ),
    ]
