# Generated by Django 4.1.7 on 2023-05-20 07:21

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('sale', 'medicine'), name='unique sale and med'),
        ),
    ]
