# Generated by Django 4.1.7 on 2023-05-12 18:12

from django.db import migrations

def apply_migration(apps, schema_editor):
    Day = apps.get_model('core', 'Day')
    Day.objects.bulk_create([
        Day(name=u'Saturday'),
        Day(name=u'Sunday'),
        Day(name=u'Monday'),
        Day(name=u'Tuesday'),
        Day(name=u'Wednesday'),
        Day(name=u'Thursday'),
        Day(name=u'Friday'),
    ])

def revert_migration(apps, schema_editor):
    Day = apps.get_model('core', 'Day')
    Day.objects.filter(
        name__in=[
            u'Saturday',
            u'Sunday',
            u'Monday',
            u'Tuesday',
            u'Wednesday',
            u'Thursday',
            u'Friday',
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]

