# Generated by Django 4.1.7 on 2023-05-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_saleitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='unique sale and med',
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('medicine', 'sale')},
        ),
    ]
