from reportlab.lib.units import inch
from datetime import date

def blank_page(c,pharmacy,order_id):
    c.translate(0.5*inch,inch)
    c.setFont("Helvetica", 14)
    c.setStrokeColorRGB(0.1,0.8,0.1)
    c.setFillColorRGB(0,0,1) 
    c.drawString(0, 9*inch, f"Pharmacy: {pharmacy.name}")
    c.drawString(0, 8.7*inch, f"City: {pharmacy.city}")
    c.setFillColorRGB(0,0,0) 
    c.line(0,8.6*inch,6.8*inch,8.6*inch)
    c.drawString(5.6*inch,9.5*inch,f'Bill No :# {order_id}')
    dt = date.today().strftime('%Y-%m-%d %H:%m')
    c.drawString(5.6*inch,9.3*inch,dt)
    c.setFont("Helvetica", 8)
    c.setFillColorRGB(1,0,0)
    c.setFont("Times-Bold", 40)
    c.drawString(4.3*inch,8.7*inch,'INVOICE')
    c.rotate(45)
    c.setFillColorCMYK(0,0,0,0.08)
    c.setFont("Helvetica", 140)
    c.rotate(-45) 
    c.setFillColorRGB(0,0,0) 
    c.setFont("Times-Roman", 22)
    c.drawString(0,8.3*inch,'Medicines')
    c.drawString(4.5*inch,8.3*inch,'Price')
    c.drawString(5.65*inch,8.3*inch,'No')
    c.drawString(6.4*inch,8.3*inch,'Total')
    c.setStrokeColorCMYK(0,0,0,1) 
    c.line(3.9*inch,8.3*inch,3.9*inch,1.7*inch)
    c.line(5.5*inch,8.3*inch,5.5*inch,1.7*inch)
    c.line(6.2*inch,8.3*inch,6.2*inch,1.7*inch)
    c.line(0.01*inch,1.5*inch,7.5*inch,1.5*inch)
    c.setFont("Times-Bold", 22)
    c.drawString(0.5*inch,0.8*inch,'Total')
    c.setFont("Times-Roman", 22)
    c.drawString(5.6*inch,-0.1*inch,'Signature')
    c.setStrokeColorRGB(0,0,0) 
    c.setFont("Helvetica", 8) 
    c.setFillColorRGB(1,0,0) 
    
    return c
